### ISSUE TITLE
JGO is calling

### ISSUE THREAD

**Issue by Secrets2L** [Hydroque/LuaConsole#1]
Hey we moved to discord. We would love to have you back and catch up with your latest projects! (I am an OP along with NegativeZero, Ray, and ra4king) but mostly everyone is here.

**Comment by Secrets2L** [comment]
Hey a few of us JGOers are gonna be in west virginia u should hop on so we can talk about meetups

**Comment by Hydroque** [comment]
Are you guys really still stalking me :)

**Comment by Secrets2L** [comment]
want the discord link?

**Comment by Secrets2L** [comment]
come on cody just stop in for an hour
